name: tests

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  gut:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        godot-version:
          - 4.0.4-stable
          - 4.1.4-stable
          - 4.2.2-stable
          - 4.3.0-stable
          - 4.4.1-stable
          - 4.5.2-stable
          - 4.6.3-stable
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: lihop/setup-godot@v3
        with:
          version: ${{ matrix.godot-version }}

      - name: Import project
        run: godot --headless --path . --import

      - name: Run GUT
        run: |
          godot --headless --path . -s addons/gut/gut_cmdln.gd \
            -gdir=res://tests -ginclude_subdirs -gexit
